#pragma once


#include "acme/_.h"


#ifdef _REGULAR_EXPRESSION_PCRE2_LIBRARY
#define CLASS_DECL_REGULAR_EXPRESSION_PCRE2  CLASS_DECL_EXPORT
#else
#define CLASS_DECL_REGULAR_EXPRESSION_PCRE2  CLASS_DECL_IMPORT
#endif



