#!/bin/bash

. ./gnome_setup


. add_aura_gnome


add_item()
{

   cd $BASE_DIR
   zip "gnome/$PACKAGE_NAME.zip" "$1"

}


add_item app_app
add_item libdraw2d_cairo.so


cd $BASE_DIR
cp "gnome/$PACKAGE_NAME.zip" /store/ubuntu/gnome/

