#!/bin/bash

./setup
PACKAGE_NAME=app_app


BASE_DIR=$HOME/solution/basis/time-linux/x64/basis


add_item()
{

   cd $BASE_DIR
   zip "$PACKAGE_NAME.zip" "$1"

}

add_item app_app
add_item libacme.so
add_item libacme_linux.so
add_item libacme_posix.so
add_item libapex.so
add_item libapex_linux.so
add_item libapex_posix.so
add_item libaqua.so
add_item libaura.so
add_item libaura_linux.so
add_item libaura_posix.so
add_item libdraw2d_cairo.so
add_item libwindowing_x11.so
add_item libnode_linux.so
