#!/bin/bash

pushd /ben/app
git pull
popd

pushd /ben/operating-system-raspbian
git pull
popd

pushd /ben/quasar-science
git pull
popd

pushd /ben/third
git pull
popd


#svn commit -F /ben/app-ca2/raspi-commit.txt /ben/app-ca2
#git commit -F /ben/app-ca2/raspi-commit.txt /ben/operating-system-raspbian
#git commit -F /ben/app-ca2/raspi-commit.txt /ben/quasar-science
#git commit -F /ben/app-ca2/raspi-commit.txt /ben/third

#git push origin master /ben/app
#git push origin master /ben/operating-system-raspbian
#git push origin master /ben/quasar-science
#git push origin master /ben/third


