#pragma once


enum ENUM_ID : ::uptr
{

   ID_INVALID = UINTPTR_MAX,

   ID_NONE = 0,

   // here it is proper just no-argument updates
   ID_INITIAL_UPDATE = 0x4000,
   ID_PRE_CLOSE_DOCUMENT,
   ID_NEW_DOCUMENT,
   ID_CLOSE_DOCUMENT,
   ID_OPEN_DOCUMENT,
   ID_SAVE_DOCUMENT,
   ID_EVENT,
   ID_UPDATE,
   ID_FULL,
   ID_DOCUMENT,
   ID_TOPIC_OK,
   ID_INITIALIZE,
   ID_BROWSE,
   ID_SYNCHRONIZE_PATH,
   ID_FILTER,
   ID_FORM,
   ID_REDRAW,
   ID_SOUL,
   ID_CREATE,
   ID_DESTROY,
   ID_FINISH,
   ID_DIALOG_RESULT,
   ID_COMPLETE,


};
