#pragma once


enum ENUM_MESSAGE : ::i32
{

   MESSAGE_UNDEFINED = -1,

   MESSAGE_NULL = 0,

   MESSAGE_CREATE = 1,
   MESSAGE_DESTROY = 2,
   MESSAGE_REPOSITION = 3,
   MESSAGE_SIZE = 5,
   MESSAGE_ACTIVATE = 6,
   MESSAGE_SET_FOCUS = 7,
   MESSAGE_KILL_FOCUS = 8,
   MESSAGE_ENABLE = 10,
   MESSAGE_SET_TEXT = 12,
   MESSAGE_PAINT = 15,
   MESSAGE_CLOSE = 16,
   MESSAGE_QUIT = 18,


}; // ENUM_MESSAGE