#pragma once


enum enum_impact : long long
{

   e_impact_none,
   e_impact_main = MAIN_IMPACT,
   e_impact_a2 = 2,
   e_impact_context_menu = CONTEXT_MENU_IMPACT,
   e_impact_menu = MENU_IMPACT,
   e_impact_main_switcher = MAIN_SWITCHER_IMPACT,
   e_impact_devedge = DEVEDGE_IMPACT,
   e_impact_gcom = GCOM_IMPACT,
   e_impact_options = OPTIONS_IMPACT,
   e_impact_edit = EDIT_IMPACT,
   e_impact_weather = WEATHER_IMPACT,
   e_impact_audio_devices = AUDIO_DEVICES_IMPACT,
   e_impact_test = TEST_IMPACT,
   e_impact_actionarea = ACTION_AREA_IMPACT,
   e_impact_desk = DESK_IMPACT,
   e_impact_configuration = CONFIGURATION_IMPACT,
   e_impact_properties = PROPERTIES_IMPACT,
   e_impact_help = HELP_IMPACT,
   e_impact_first_pane = FIRST_PANE,
   e_impact_app_options = APP_OPTIONS_IMPACT,
   e_impact_context_options = CONTEXT_OPTIONS_IMPACT,
   e_impact_about = ABOUT_IMPACT,
   e_impact_tic_tac_toe = 0x1000,
   e_impact_playlist,
   e_impact_karaoke,
   e_impact_new,
   e_impact_primary_command,
   e_impact_second_command,
   e_impact_three_action_launch,
   e_impact_media_library,
   e_impact_media_library_all_media,
   e_impact_media_library_explorer,
   e_impact_media_library_library_explorer,
   e_impact_media_library_file_system_explorer,
   e_impact_options_folders,
   e_impact_options_file_association,
   e_impact_options_karaoke,
   e_impact_options_audio_devices,
   e_impact_local_computer_list,
   e_impact_cloud_computer_list,
   e_impact_simple_drawing,
   e_impact_simple_change_grub_default_entry,
   e_impact_simple_form,
   e_impact_visual_click,
   e_impact_chronometer,
   e_impact_by_weekday,
   e_impact_transform,
   e_impact_image,
   e_impact_communication,
   e_impact_contact,
   e_impact_resident,
   e_impact_html_edit,
   e_impact_html_stage,
   e_impact_solution,
   e_impact_bind,
   e_impact_sha1,
   e_impact_crc,
   e_impact_md5,
   e_impact_text_format,
   e_impact_impacters,
   e_impact_library,
   e_impact_video,
   e_impact_modes,
   e_impact_rx,
   e_impact_app,
   e_impact_document,
   e_impact_file_properties,
   e_impact_installer,
   e_impact_appearance,
   e_impact_keyboard_layout,
   e_impact_language,
   e_impact_backup,
   e_impact_all,
   e_impact_active,
   e_impact_filter,
   e_impact_find,
   e_impact_computer_list,
   e_impact_announce,
   e_impact_announce_switcher,
   e_impact_midi_track_events,
   e_impact_launcher,
   e_impact_description,
   e_impact_rich_edit,
   e_impact_update,
   e_impact_store,
   
   
   e_impact_base = BASE_IMPACT,
   
   
   e_impact_tooling= 1 << 20,
   e_impact_filemanager = FILEMANAGER_IMPACT,
   e_impact_filemanager_main,
   e_impact_filemanager_save,
   e_impact_filemanager_tabbed = FILEMANAGER_IMPACT + TABBED_GROUP,
   e_impact_filemanager_list = FILEMANAGER_IMPACT + LIST_GROUP,
   e_impact_filemanager_folder_selection_list = FILEMANAGER_IMPACT + FOLDER_SELECTION_LIST_GROUP,
   
   
   e_impact_modifying = 1 << 21,
   e_impact_color_sel = COLORSEL_IMPACT,
   e_impact_font_sel = FONTSEL_IMPACT,
   

   e_impact_multitasking = 1 << 22,

};



