#pragma once


enum e_impact : ::i64
{

   impact_none,
   impact_main = MAIN_IMPACT,
   impact_a2 = 2,
   impact_context_menu = CONTEXT_MENU_IMPACT,
   impact_menu = MENU_IMPACT,
   impact_main_switcher = MAIN_SWITCHER_IMPACT,
   impact_devedge = DEVEDGE_IMPACT,
   impact_gcom = GCOM_IMPACT,
   impact_options = OPTIONS_IMPACT,
   impact_edit = EDIT_IMPACT,
   impact_weather = WEATHER_IMPACT,
   impact_audio_devices = AUDIO_DEVICES_IMPACT,
   impact_test = TEST_IMPACT,
   impact_actionarea = ACTION_AREA_IMPACT,
   impact_desk = DESK_IMPACT,
   impact_configuration = CONFIGURATION_IMPACT,
   impact_properties = PROPERTIES_IMPACT,
   impact_help = HELP_IMPACT,
   impact_first_pane = FIRST_PANE,
   impact_tic_tac_toe,
   impact_playlist,
   impact_karaoke,
   impact_new,
   impact_primary_command,
   impact_second_command,
   impact_three_action_launch,
   impact_media_library,
   impact_media_library_all_media,
   impact_media_library_explorer,
   impact_media_library_library_explorer,
   impact_media_library_file_system_explorer,
   impact_options_folders,
   impact_options_file_association,
   impact_options_karaoke,
   impact_options_audio_devices,
   impact_local_computer_list,
   impact_cloud_computer_list,
   impact_simple_drawing,
   impact_simple_change_grub_default_entry,
   impact_simple_form,
   impact_visual_click,
   impact_chronometer,
   impact_by_weekday,
   impact_transform,
   impact_image,
   impact_communication,
   impact_contact,
   impact_resident,
   impact_html_edit,
   impact_html_stage,
   impact_solution,
   impact_bind,
   impact_sha1,
   impact_crc,
   impact_md5,
   impact_text_format,
   impact_viewers,
   impact_library,
   impact_video,
   impact_modes,
   impact_rx,
   impact_app,
   impact_document,
   impact_file_properties,
   impact_installer,
   impact_appearance,
   impact_keyboard_layout,
   impact_language,
   impact_backup,
   impact_all,
   impact_active,
   impact_filter,
   impact_find,
   impact_computer_list,
   impact_announce,
   impact_announce_switcher,
   impact_midi_track_events,
   impact_launcher,
   impact_description,
   impact_rich_edit,


   impact_base = 100'000,


   impact_tooling= 1'000'000,
   impact_filemanager = FILEMANAGER_IMPACT,
   impact_filemanager_main,
   impact_filemanager_save,
   impact_filemanager_tabbed = FILEMANAGER_IMPACT + TABBED_GROUP,
   impact_filemanager_list = FILEMANAGER_IMPACT + LIST_GROUP,
   impact_filemanager_folder_selection_list = FILEMANAGER_IMPACT + FOLDER_SELECTION_LIST_GROUP,


   impact_modifying = 2'000'000,
   impact_color_sel = COLORSEL_IMPACT,
   impact_font_sel = FONTSEL_IMPACT,


};



