#pragma once

enum enum_element : ::i64
{

   e_element_none,



   // user element
   e_element_frame_window = 0x40000000, // 1'073'741'824
   e_element_tab,
   e_element_tab_layout_background,
   e_element_tab_client_background,
   e_element_tab_item_background,
   e_element_tab_near_scroll,
   e_element_tab_far_scroll,
   e_element_close_tab_button,
   e_element_status_image,
   e_element_text,
   e_element_list,
   e_element_item_text,
   e_element_item_background,
   e_element_item_border,
   e_element_hilite_text,
   e_element_icon,
   e_element_background,
   e_element_separator,
   e_element_face,
   e_element_border,
   e_element_lite_border,
   e_element_client,
 //e_element_resize,
   e_element_non_client, // but m_bMouseHoverOnCapture ?
   e_element_area,
   e_element_drop_down,
   e_element_combo_edit,
   e_element_item,
   e_element_search_edit,
   e_element_search_ok,
   e_element_scrollbar,
   e_element_scrollbar_draw,
   e_element_scrollbar_strong,
   e_element_scrollbar_trackbar,
   e_element_scrollbar_rectA,
   e_element_scrollbar_rectB,
   e_element_scrollbar_pageA,
   e_element_scrollbar_pageB,
   e_element_margin_top,
   e_element_margin_left,
   e_element_margin_right,
   e_element_margin_bottom,
   e_element_window_title,
   e_element_image,
   e_element_close_button,
   e_element_close_icon,
   e_element_hilite,
   e_element_dark_shadow,
   e_element_button_text,
   e_element_button_background,
   e_element_button_hilite,
   e_element_button_shadow,
   e_element_button_dark_shadow,
   e_element_check,
   e_element_switch_button,
   e_element_switch_icon,
   e_element_top_left_icon,
   e_element_move_grip_minimal,
   e_element_maximize_button,
   e_element_maximize_icon,
   e_element_minimize_button,
   e_element_minimize_icon,
   e_element_resize,


   e_element_split = 10000,

   e_element_desk_launcher_1,
   e_element_desk_launcher_2,
   e_element_desk_launcher_3,
   e_element_desk_launcher_4,
   e_element_desk_launcher_5,
   e_element_desk_launcher_6,
   e_element_desk_launcher_7,
   e_element_desk_launcher_8,
   e_element_desk_launcher_last = e_element_desk_launcher_8,
   e_element_desk_close,
   e_element_desk_change_view,
   e_element_desk_change_theme,
   e_element_desk_last,

   e_element_start,
   e_element_reset,
   e_element_cancel,

};



namespace user
{


   enum enum_flag
   {

      e_flag_none,
      e_flag_border = 1 << 0,
      e_flag_modifier_impact = 1 << 1,
      e_flag_tool_impact = 1 << 2,
      e_flag_blur_background = 1 << 3,
      e_flag_hide_all_others_on_show = 1 << 4,
      e_flag_hidid_on_show = 1 << 5,
      e_flag_strict_update = 1 << 6,
      e_flag_hide_on_kill_focus = 1 << 7,
      e_flag_background_bypass = 1 << 8,

   };

   enum enum_key : ::i32
   {

      e_key_none,
      e_key_refer_to_text_member,
      e_key_0,
      e_key_1,
      e_key_2,
      e_key_3,
      e_key_4,
      e_key_5,
      e_key_6,
      e_key_7,
      e_key_8,
      e_key_9,
      e_key_a,
      e_key_b,
      e_key_c,
      e_key_d,
      e_key_e,
      e_key_f,
      e_key_g,
      e_key_h,
      e_key_i,
      e_key_j,
      e_key_k,
      e_key_l,
      e_key_m,
      e_key_n,
      e_key_o,
      e_key_p,
      e_key_q,
      e_key_r,
      e_key_s,
      e_key_t,
      e_key_u,
      e_key_v,
      e_key_w,
      e_key_x,
      e_key_y,
      e_key_z,
      e_key_semicolon,
      e_key_semicolon2,
      e_key_semicolon3,
      e_key_comma,
      e_key_dot,
      e_key_back,
      e_key_delete,
      e_key_space,
      e_key_right,
      e_key_down,
      e_key_left,
      e_key_up,
      e_key_prior,
      e_key_next,
      e_key_return,
      e_key_home,
      e_key_end,
      e_key_tab,
      e_key_capslock,
      e_key_hyphen,
      e_key_slash2,
      e_key_backslash2,
      e_key_closebracket2,
      e_key_openbracket2,
      e_key_til2,
      e_key_acute2,
      e_key_equal,
      e_key_escape,
      e_key_apostrophe2,
      e_key_numpad_0,
      e_key_numpad_1,
      e_key_numpad_2,
      e_key_numpad_3,
      e_key_numpad_4,
      e_key_numpad_5,
      e_key_numpad_6,
      e_key_numpad_7,
      e_key_numpad_8,
      e_key_numpad_9,
      e_key_print_screen,
      e_key_f1,
      e_key_f2,
      e_key_f3,
      e_key_f4,
      e_key_f5,
      e_key_f6,
      e_key_f7,
      e_key_f8,
      e_key_f9,
      e_key_f10,
      e_key_f11,
      e_key_f12,

      e_key_left_shift = 1 << 12,
      e_key_right_shift = 1 << 13,
      e_key_shift = e_key_left_shift | e_key_right_shift,
      e_key_left_control = 1 << 14,
      e_key_right_control = 1 << 15,
      e_key_control = e_key_left_control | e_key_right_control,
      e_key_left_alt = 1 << 16,
      e_key_right_alt = 1 << 17,
      e_key_alt = e_key_left_alt | e_key_right_alt,
      e_key_left_command = 1 << 18,
      e_key_right_command = 1 << 19,
      e_key_command = e_key_left_command | e_key_right_command,
      e_key_system_left_command = 1 << 20,
      e_key_system_right_command = 1 << 21,
      e_key_system_command = e_key_system_left_command | e_key_system_right_command,
      e_key_left_button = 1LL <<24,
      e_key_right_button = 1LL << 25,
      e_key_middle_button = 1LL << 26,

   };


} // namespace user




