//
// Created by camilo on 2023-10-10 21:59 <3ThomasBorregaardSorensen!!.
//
#pragma once


namespace user
{


   enum enum_key : huge_integer
   {

      e_key_none,


      e_key_refer_to_text_member,


      e_key_0,
      e_key_1,
      e_key_2,
      e_key_3,
      e_key_4,
      e_key_5,
      e_key_6,
      e_key_7,
      e_key_8,
      e_key_9,
      e_key_a,
      e_key_b,
      e_key_c,
      e_key_d,
      e_key_e,
      e_key_f,
      e_key_g,
      e_key_h,
      e_key_i,
      e_key_j,
      e_key_k,
      e_key_l,
      e_key_m,
      e_key_n,
      e_key_o,
      e_key_p,
      e_key_q,
      e_key_r,
      e_key_s,
      e_key_t,
      e_key_u,
      e_key_v,
      e_key_w,
      e_key_x,
      e_key_y,
      e_key_z,
      e_key_semicolon,
//      e_key_semicolon2,
//      e_key_semicolon3,
      e_key_comma,
      e_key_dot,
      e_key_back,
      e_key_delete,
      e_key_space,
      e_key_right,
      e_key_down,
      e_key_left,
      e_key_up,
      e_key_page_up,
      e_key_page_down,
      e_key_return,
      e_key_home,
      e_key_end,
      e_key_tab,
      e_key_capslock,
      e_key_hyphen,
      e_key_slash,
      e_key_backslash,
      e_key_close_bracket,
      e_key_open_bracket,
      e_key_til,
      e_key_grave,
      e_key_acute,
      e_key_equal,
      e_key_escape,
      e_key_apostrophe,
      e_key_numpad_0,
      e_key_numpad_1,
      e_key_numpad_2,
      e_key_numpad_3,
      e_key_numpad_4,
      e_key_numpad_5,
      e_key_numpad_6,
      e_key_numpad_7,
      e_key_numpad_8,
      e_key_numpad_9,
      e_key_print_screen,
      e_key_f1,
      e_key_f2,
      e_key_f3,
      e_key_f4,
      e_key_f5,
      e_key_f6,
      e_key_f7,
      e_key_f8,
      e_key_f9,
      e_key_f10,
      e_key_f11,
      e_key_f12,
      e_key_f13,
      e_key_f14,
      e_key_f15,
      e_key_f16,
      e_key_f17,
      e_key_f18,
      e_key_f19,
      e_key_f20,
      e_key_f21,
      e_key_f22,
      e_key_f23,
      e_key_f24,
      e_key_plus,
      e_key_minus,
      e_key_plus_oem,
      e_key_minus_oem,
      e_key_left_bracket,
      e_key_right_bracket,
      e_key_sysreq,
      e_key_mode,
      e_key_non_us_back_slash,
      e_key_brightness_down,
      e_key_brightness_up,
      e_key_numpad_multiply,
      e_key_numpad_divide,
      e_key_numpad_equal,
      e_key_numpad_plus,
      e_key_numpad_minus,
      e_key_numpad_period,
      e_key_numpad_enter,
      e_key_numlock_clear,
      e_key_international1,
      e_key_international2,
      e_key_international3,
      e_key_international4,
      e_key_international5,
      e_key_international6,
      e_key_insert,
      e_key_volume_down,
      e_key_volume_up,
      e_key_power,
      e_key_pause,
      e_key_left_gui,
      e_key_right_gui,
      e_key_cancel,
      e_key_again,
      e_key_copy,
      e_key_paste,
      e_key_sleep,
      e_key_app1,
      e_key_app2,
      e_key_www,
      e_key_mail,
      e_key_ac_bookmarks,
      e_key_computer,
      e_key_ac_back,
      e_key_ac_forward,
      e_key_eject,
      e_key_audionext,
      e_key_audioplay,
      e_key_audioprev,
      e_key_audiostop,
      e_key_audiorewind,
      e_key_ac_home,
      e_key_ac_refresh,
      //e_key_again,
      e_key_ac_search,
      e_key_stop,
      e_key_media_select,
      /* 227 */   e_key_display_switch,
      /* 228 */   e_key_kbdillumtoggle,
      /* 229 */   e_key_kbdillumdown,
      /* 230 */   e_key_kbdillumup,
      e_key_period,
      e_key_scroll_lock,
      e_key_mute,
      e_key_application,
      e_key_find,
      e_key_cut,
      e_key_help,
      e_key_calculator,
      e_key_undo,




      e_key_with_no_modifier_mask = 0xffffffff,


      e_key_left_shift = 1LL << 32,
      e_key_right_shift = 1LL << 33,
      e_key_shift = e_key_left_shift | e_key_right_shift,
      e_key_left_control = 1LL << 34,
      e_key_right_control = 1LL << 35,
      e_key_control = e_key_left_control | e_key_right_control,
      e_key_left_alt = 1LL << 36,
      e_key_right_alt = 1LL << 37,
      e_key_alt = e_key_left_alt | e_key_right_alt,
      e_key_left_command = 1LL << 38,
      e_key_right_command = 1LL << 39,
      e_key_command = e_key_left_command | e_key_right_command,
      e_key_system_left_command = 1LL << 40,
      e_key_system_right_command = 1LL << 41,
      e_key_system_command = e_key_system_left_command | e_key_system_right_command,


      e_key_left_button = 1LL << 48,
      e_key_right_button = 1LL << 49,
      e_key_middle_button = 1LL << 50,

   };


} // namespace user





