// Copyright (C) 2009,2010,2011,2012 GlavSoft LLC.
// All rights reserved.
//
//-------------------------------------------------------------------------
// This file is part of the TightVNC software.  Please visit our Web site:
//
//                       http://www.tightvnc.com/
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, w_rite to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//-------------------------------------------------------------------------
//

#pragma once


#include "acme/subsystem/_common_header.h"
//#include "acme/subsystem/Exception.h"
//#include "subsystem/subsystem.h"

#include "acme/subsystem/node/SystemException.h"

namespace subsystem
{
   /**
    * ServiceControlManagerClient own exception that can be generated by
    * some of ServiceControlManagerClient methods.
    */
   class CLASS_DECL_ACME ServiceControlManagerClientException :
      virtual public SystemException
   {
   public:
      /**
       * Service already stopped and cannot be stopped.
       */
      const static int ERROR_ALREADY_STOPPED = 0;
      /**
       * Timeout expired while waiting for service to stop.
       */
      const static int ERROR_STOP_TIMEOUT = 1;
      /**
       * Service alreadying running and cannot be started.
       */
      const static int ERROR_ALREADY_RUNNING = 2;
      /**
       * Timeout expired while waiting for service to start.
       */
      const static int ERROR_START_TIMEOUT = 3;
   public:
      /**
       * Creates new ServiceControlManagerClient exception.
       * @param scmErrCode service client manager client own error code,
       * see ServiceControlManagerClientException public constants for information.
       */
      ServiceControlManagerClientException(int iServiceControlManagerErrorCode);
      /**
       * Returns scm error code.
       */
      int getServiceControlManagerErrorCode() const;
   // private:
   //    /**
   //     * scm own error code.
   //     */
       int m_iServiceControlManagerErrorCode;
   };

   /**
    * Service client manager client.
    *
    * Gives access to install, remove, start, stop services and queries status
    * of service.
    */
   class CLASS_DECL_ACME ServiceControlManagerClientInterface :
   virtual public ::subsystem::particle_interface
   {
   public:
      /**
       * Creates new ServiceControlManagerClient.
       * @param desiredAccess desired acess (see OpenServiceControlManageranager WinAPI function description
       * for details).
       * @throws SystemException on fail.
       */
      //ServiceControlManagerClient(unsigned int desiredAccess = SC_MANAGER_ALL_ACCESS);

      //ServiceControlManagerClientInterface();
      /**
       * Destructor, closes ServiceControlManagerClient.
       */
      virtual ~ServiceControlManagerClientInterface() = 0;


      virtual void initialize_service_control_manager_client(unsigned int desiredAccess = 0) = 0;

      /**
       * Registers new service in system.
       * @param name name of service.
       * @param nameToDisplay name to display in services ::list_base.
       * @param binPath full path to service binary.
       * @param dependencies [optional] service dependencies.
       * @throws SystemException on fail.
       */
      virtual void installService(const ::scoped_string & scopedstrName, const ::scoped_string & scopedstrNameToDisplay,
                          const ::scoped_string & scopedstrBinPath, const ::scoped_string & scopedstrDependencies = "") = 0;
      /**
       * Unregisters existing service from services.
       * @param name name of service to unregister.
       * @throws SystemException on fail.
       */
      virtual void removeService(const ::scoped_string & scopedstrName) = 0;
      /**
       * Starts existing service.
       * @param name name of service to start.
       * @param waitCompletion if true, wait until the status becomes
       *   SERVICE_RUNNING.
       * @throws SystemException, ServiceControlManagerClientException on fail.
       */
      virtual void startService(const ::scoped_string & scopedstrName, bool waitCompletion = false) = 0
    ;
      /**
       * Stops running service execution.
       * @param name name of service to stop.
       * @param waitCompletion if true, wait until the status becomes
       *   SERVICE_STOPPED.
       * @throws SystemException, ServiceControlManagerClientException on fail.
       */
      virtual void stopService(const ::scoped_string & scopedstrName, bool waitCompletion = false) = 0;


   // private:
   //    /**
   //     * Gets current state of existing service specified by handle.
   //     * @param hService handle of the service.
   //     * @return current service state.
   //     * @throws SystemException on failure.
   //     */
   //    DWORD getServiceState(SC_HANDLE hService) const;
   //
   // private:
   //    /** Service client manager handle. */
   //    SC_HANDLE m_managerHandle;
   };



   /**
 * Service client manager client.
 *
 * Gives access to install, remove, start, stop services and queries status
 * of service.
 */
   class CLASS_DECL_ACME ServiceControlManagerClient :
   virtual public ::subsystem::composite<ServiceControlManagerClientInterface>
   {
   public:
      /**
       * Creates new ServiceControlManagerClient.
       * @param desiredAccess desired acess (see OpenServiceControlManageranager WinAPI function description
       * for details).
       * @throws SystemException on fail.
       */
      //ServiceControlManagerClient(DWORD desiredAccess = SC_MANAGER_ALL_ACCESS);
      ServiceControlManagerClient(unsigned int desiredAccess = 0);
      //ServiceControlManagerClient();
      /**
       * Destructor, closes ServiceControlManagerClient.
       */
      ~ServiceControlManagerClient() override;


      //void initialize_service_control_manager_client(unsigned int desiredAccess = SC_MANAGER_ALL_ACCESS) override;
      void initialize_service_control_manager_client(unsigned int desiredAccess = 0) override;
      /**
       * Registers new service in system.
       * @param name name of service.
       * @param nameToDisplay name to display in services ::list_base.
       * @param binPath full path to service binary.
       * @param dependencies [optional] service dependencies.
       * @throws SystemException on fail.
       */
      void installService(const ::scoped_string & scopedstrName, const ::scoped_string & scopedstrNameToDisplay,
                          const ::scoped_string & scopedstrBinPath, const ::scoped_string & scopedstrDependencies = "") override;
      /**
       * Unregisters existing service from services.
       * @param name name of service to unregister.
       * @throws SystemException on fail.
       */
      void removeService(const ::scoped_string & scopedstrName) override;
      /**
       * Starts existing service.
       * @param name name of service to start.
       * @param waitCompletion if true, wait until the status becomes
       *   SERVICE_RUNNING.
       * @throws SystemException, ServiceControlManagerClientException on fail.
       */
      void startService(const ::scoped_string & scopedstrName, bool waitCompletion = false) override
    ;
      /**
       * Stops running service execution.
       * @param name name of service to stop.
       * @param waitCompletion if true, wait until the status becomes
       *   SERVICE_STOPPED.
       * @throws SystemException, ServiceControlManagerClientException on fail.
       */
      void stopService(const ::scoped_string & scopedstrName, bool waitCompletion = false) override
    ;

   // private:
   //    /**
   //     * Gets current state of existing service specified by handle.
   //     * @param hService handle of the service.
   //     * @return current service state.
   //     * @throws SystemException on failure.
   //     */
   //    DWORD getServiceState(SC_HANDLE hService) const;
   //
   // private:
   //    /** Service client manager handle. */
   //    SC_HANDLE m_managerHandle;
   };


} // namespace subsystem


