BEGIN_FACTORY(app_just_message_box) 
FACTORY_DEPENDENCY(draw2d_gdiplus) 
FACTORY_DEPENDENCY(node_windows) 
FACTORY_DEPENDENCY(windowing_win32) 
FACTORY_DEPENDENCY(write_text_win32) 
FACTORY_DEPENDENCY(app_just_message_box) 
END_FACTORY() 
