//
//  user_key_enum.h
//  base
//
//  moved from aura on 16 de Novembro de 2013
//

#pragma once
//
//
//namespace user
//{
//
//
//   enum e_key
//   {
//
//      key_none,
//      key_refer_to_text_member,
//      key_0,
//      key_1,
//      key_2,
//      key_3,
//      key_4,
//      key_5,
//      key_6,
//      key_7,
//      key_8,
//      key_9,
//      key_a,
//      key_b,
//      key_c,
//      key_d,
//      key_e,
//      key_f,
//      key_g,
//      key_h,
//      key_i,
//      key_j,
//      key_k,
//      key_l,
//      key_m,
//      key_n,
//      key_o,
//      key_p,
//      key_q,
//      key_r,
//      key_s,
//      key_t,
//      key_u,
//      key_v,
//      key_w,
//      key_x,
//      key_y,
//      key_z,
//      key_semicolon,
//      key_semicolon2,
//      key_semicolon3,
//      key_comma,
//      key_dot,
//      key_shift,
//      key_lshift,
//      key_rshift,
//      key_control,
//      key_lcontrol,
//      key_rcontrol,
//      key_alt,
//      key_lalt,
//      key_ralt,
//      key_command,
//      key_lcommand,
//      key_rcommand,
//      key_lbutton,
//      key_rbutton,
//      key_mbutton,
//      key_back,
//      key_delete,
//      key_space,
//      key_right,
//      key_down,
//      key_left,
//      key_up,
//      key_prior,
//      key_next,
//      key_return,
//      key_home,
//      key_end,
//      key_tab,
//      key_capslock,
//      key_hyphen,
//      key_slash2,
//      key_backslash2,
//      key_closebracket2,
//      key_openbracket2,
//      key_til2,
//      key_acute2,
//      key_equal,
//      key_escape,
//      key_apostrophe2,
//      key_numpad_0,
//      key_numpad_1,
//      key_numpad_2,
//      key_numpad_3,
//      key_numpad_4,
//      key_numpad_5,
//      key_numpad_6,
//      key_numpad_7,
//      key_numpad_8,
//      key_numpad_9,
//      key_print_screen,
//      key_f1,
//      key_f2,
//      key_f3,
//      key_f4,
//      key_f5,
//      key_f6,
//      key_f7,
//      key_f8,
//      key_f9,
//      key_f10,
//      key_f11,
//      key_f12,
//
//   };
//
//
//} // namespace user
//
//
//
