#pragma once


#include "base/_.h"


#ifdef _APP_EXPERIENCE_ANTHILL_LIBRARY
#define CLASS_DECL_APP_EXPERIENCE_ANTHILL  CLASS_DECL_EXPORT
#else
#define CLASS_DECL_APP_EXPERIENCE_ANTHILL  CLASS_DECL_IMPORT
#endif



