#include "framework.h"


#include "colorertake5_base_editor.cpp"
#include "colorertake5_colorertake5.cpp"
#include "colorertake5_default_error_handler.cpp"
#include "colorertake5_error_handler_writer.cpp"
#include "colorertake5_exception.cpp"
#include "colorertake5_hrc_parser_helpers.cpp"
#include "colorertake5_hrc_parser_impl.cpp"
#include "colorertake5_line_regions_compact_support.cpp"
#include "colorertake5_line_regions_support.cpp"
#include "colorertake5_line_source.cpp"
#include "colorertake5_logging.cpp"
#include "colorertake5_outliner.cpp"
#include "colorertake5_parsed_line_writer.cpp"
#include "colorertake5_parser_factory.cpp"
#include "colorertake5_region_handler.cpp"
#include "colorertake5_region_mapper_impl.cpp"
#include "colorertake5_styled_hrd_mapper.cpp"
#include "colorertake5_text_hrd_mapper.cpp"
#include "colorertake5_text_lines.cpp"
#include "colorertake5_text_parser_helpers.cpp"
#include "colorertake5_text_parser_impl.cpp"

