#pragma once



#include "colorertake5_features.h"
#include "colorertake5_exception.h"
#include "colorertake5_memory_chunks.h"
#include "colorertake5_logging.h"
#include "colorertake5_file_type.h"
#include "colorertake5_line_source.h"
#include "colorertake5_cregexp.h"
#include "colorertake5_region.h"
#include "colorertake5_scheme.h"
#include "colorertake5_region_handler.h"
#include "colorertake5_text_parser.h"
#include "colorertake5_error_handler.h"
#include "colorertake5_hrc_parser.h"
#include "colorertake5_hrc_parser_helpers.h"
#include "colorertake5_hrc_parser_impl.h"
#include "colorertake5_text_parser_helpers.h"
#include "colorertake5_text_parser_impl.h"
#include "colorertake5_text_lines.h"
#include "colorertake5_error_handler_writer.h"
#include "colorertake5_region_define.h"
#include "colorertake5_region_mapper.h"
#include "colorertake5_styled_region.h"
#include "colorertake5_text_region.h"
#include "colorertake5_line_region.h"
#include "colorertake5_line_regions_support.h"
#include "colorertake5_line_regions_compact_support.h"
#include "colorertake5_file_type_impl.h"
#include "colorertake5_text_parser.h"
#include "colorertake5_hrc_parser.h"
#include "colorertake5_default_error_handler.h"
#include "colorertake5_region_mapper_impl.h"
#include "colorertake5_styled_hrd_mapper.h"
#include "colorertake5_text_hrd_mapper.h"
#include "colorertake5_parser_factory_exception.h"
#include "colorertake5_parser_factory.h"
#include "colorertake5_editor_listener.h"
#include "colorertake5_pair_match.h"
#include "colorertake5_base_editor.h"
#include "colorertake5_parsed_line_writer.h"
#include "colorertake5_text_console_impacter.h"
#include "colorertake5_outline_item.h"
#include "colorertake5_outliner.h"


#include "colorertake5_colorertake5.h"
