#include "framework.h"


//#include "android_arua.cpp"
#include "android_c.cpp"
#include "android_cross_win_file.cpp"
#include "android_cross_win_gdi.cpp"
#include "android_debug.cpp"
#include "android_file.cpp"
#include "android_file_watcher.cpp"
#include "android_launcher.cpp"
#include "android_library.cpp"
#include "android_locale.cpp"
#include "android_lock.cpp"
#include "android_main.cpp"
#include "android_MessageBoxA.cpp"
#include "android_message_loop.cpp"
#include "android_multitasking.cpp"
#include "android_process.cpp"
#include "android_process_pid.cpp"
#include "android_simple_shell_launcher.cpp"
#include "android_small_ipca_channel.cpp"
#include "android_impact_bitmap.cpp"
#include "android_window_android.cpp"
#include "android_window_buffer.cpp"
#include "android_window_impl.cpp"
#include "android_win_base.cpp"
#include "android_windowing.cpp"


